models.py
#models
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime


db = SQLAlchemy()

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150), nullable=False)
    task = db.Column(db.String(150), nullable=False)
    description = db.Column(db.String(500), nullable=True)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)


    def __repr__(self):
        return f'Todo {self.title}'

app.py
from flask import Flask
from config import Config
from models import db
from routes import todo_db

app = Flask(__name__)
app.config.from_object(Config)

#veritabanı başlat
db.init_app(app)

#Blueprint kaydet
app.register_blueprint(todo_db)

#Veritabnı tablo olusturma
with app.app_context():
    db.create_all()


if __name__ == "__main__":
    app.run(debug=True)

routes.py
#routes
from crypt import methods

from flask import Blueprint, render_template, request, redirect, url_for
from models import db, Todo

#blueprint olusturma
todo_db = Blueprint('todo',__name__)

#Anasayfa
@todo_db.route("/", methods=['POST','GET'])
def index():
    todos = Todo.query.all()
    return render_template("index.html", todos=todos)


#Görev olusturma
@todo_db.route("/create", methods=['POST','GET'])
def create_task():
    if request.method == 'POST':
        title = request.form['title']
        task = request.form['task']
        description = request.form.get('description')


        new_task = Todo(title=title, task=task, description=description)
        db.session.add(new_task)
        db.session.commit()
        return redirect(url_for('todo.index'))
    return render_template('create_task.html')


#Görev silme
@todo_db.route("/delete/<int:id>", methods=['POST','DELETE'])
def delete_task(id):
    if request.method == 'POST':
        if request.form.get('_method') == 'DELETE':
            task = Todo.query.get_or_404(id)
            db.session.delete(task)
            db.session.commit()
            return redirect(url_for('todo.index'))


#Görev detay sayfası
@todo_db.route('/task/<int:id>')
def detail_task(id):
    task = Todo.query.get_or_404(id)
    return  render_template('task_detail.html', task=task)

templates/create_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Görev Oluştur</title>
        <link rel="stylesheet" href="/static/style.css">
</head>
<body>

<div class="new-task-container">
    <div class="add-todo">
         <h1>Yeni Görev Ekle</h1> <hr>
        <form action="{{ url_for('todo.create_task') }}" method="POST" class="form-view">
            <div class="input-title">
                <label for="title">Başlık:</label>
                <input type="text" name="title" required><br>
            </div>

            <div class="input-task">
                <label for="task">Görev:</label>
                <input type="text" name="task" required>
            </div>

            <div class="input-description">
                <label for="description">Açıklama:</label>
                <input type="text" name="description" >
                <br>
            </div>

            <div class="input-btn">
                <button type="submit">Ekle</button>
            </div>
        </form>
        <a href="{{ url_for('todo.index') }}">Geri Dön</a>
    </div>

</div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo List</title>
    <link rel="stylesheet" href="/static/style.css">
</head>
<body>
    <nav>
        <h1 class="nav-title">My Todo</h1>
        <div class="nav-search">
            <input type="text" placeholder="Search a Todo...">
            <button type="submit" class="submit-btn">Search</button>
            <button type="submit" class="add-task-btn"> <a href="{{ url_for('todo.create_task') }}">+ Add</a> </button>
        </div>
    </nav>

    <h1>Todo List</h1>
    <hr>
    <div class="generate-container">
        <div class="task-container">
            {% for todo in todos %}
                <div class="task-box">
                    <h2>{{ todo.title }}</h2>
                    <p>{{ todo.task }}</p>
                    <p>{{ todo.description }}</p>


                    <div class="details">
                    <a href="{{ url_for('todo.detail_task', id=todo.id) }}" style="color: blue;">Detaylar</a>
                    <form action="{{ url_for('todo.delete_task', id=todo.id) }}" method="POST" style="display:inline;">
                    </div>
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="submit" style="color: red; background: none; border: none; cursor: pointer; font-size: 16px;">Sil</button>
                    </form>
                </div>
            {% endfor %}
        </div>

    </div>
</body>
</html>

templates/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ task.title }}</title>
    <link rel="stylesheet" href="/static/style.css">
</head>
<body>
<div class="detail-box">
    <h1>{{ task.title }}</h1>
    <p>{{ task.task }}</p>
    <p>{{ task.description }}</p>
    <p><strong>Oluşturma Tarihi:</strong>{{ task.date_created }}</p>
    <a href="{{ url_for('todo.index') }}" style="color: black; border:1px solid black; border-radius: 5px; padding: 8px; text-decoration: none; text-aling:center;">Geri Dön</a>
</div>
</body>
</html>